version: '2'
services:
  peter_libc:
    build: ./
    ports:
      - "81823:5000"
    expose:
      - "81823"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    expose:
      - "27017"
    command: mongod --smallfiles --logpath=/dev/null 